### ISSUE TITLE
Bitwarden Desktop 1.30.0+ data.json files can not be decrypted.

### ISSUE THREAD

**Issue by GurpreetKang** [GurpreetKang/BitwardenDecrypt#12]
Bitwarden Desktop 1.30.0+ adds an account switching feature and associated changes to the data.json structure which breaks BitwardenDecrypt.

The previously used "userEmail" name/value pair is no longer present, replaced with potentially multiple "email" name/value pairs.

Additional changes to the data structure are also present in 1.30.0+ data.json files.

**Comment by felixdogg** [comment]
I'm guessing that the errors i'm getting is related to the 1.30.0 update.
![image](https://user-images.githubusercontent.com/90956507/165149418-8540256d-82b8-4bfe-8131-f8a64fcf6052.png)

**Comment by GurpreetKang** [comment]
@felixdogg Yes, this is due to the change to the data.json format in recent Desktop App versions.
I'll get a fix out hopefully this week.

**Comment by pro4tlzz** [comment]
> @felixdogg Yes, this is due to the change to the data.json format in recent Desktop App versions. I'll get a fix out hopefully this week.

I'd appreciate this fix
thanks

**Comment by GurpreetKang** [comment]
Have a fix (currently testing), should be out in the next few days until I find something major wrong with it.

**Comment by pro4tlzz** [comment]
Thanks!
