### ISSUE TITLE
Bitwarden Desktop 2022.8.0 data.json files can not be decrypted

### ISSUE THREAD

**Issue by casualsailo** [GurpreetKang/BitwardenDecrypt#17]
It looks like the structure of the organizationKeys json node changed slightly in the latest version, which I think is causing the decrypting error

![Bitwarden Desktop 2022.8.0 Error](https://user-images.githubusercontent.com/16842318/183528473-041dc863-7296-4f3f-bcf4-5febcbf6aa52.png)

**Comment by GurpreetKang** [comment]
Thanks for reporting this, I'll look into this shortly.

**Comment by GurpreetKang** [comment]
Temporary fix available here: [Fix for format change in Bitwarden Desktop 2022.8.0](https://raw.githubusercontent.com/GurpreetKang/BitwardenDecrypt/0e60d2082197e186564e55cb415684222d797580/BitwardenDecrypt.py)

While this works for new data.json files from v2022.8.0, it will fail on files from older versions so I'll need to create a more robust fix before making a new release.

**Comment by GurpreetKang** [comment]
This version should fix this issue and still support previous data.json files:
https://raw.githubusercontent.com/GurpreetKang/BitwardenDecrypt/c604c2968e4f0f55344e11a5b97a4bc0e3c4ca32/BitwardenDecrypt.py

Please let me know if it resolves the issue for you.

**Comment by GurpreetKang** [comment]
Closed by https://github.com/GurpreetKang/BitwardenDecrypt/commit/6a5f757de240dd8df1bb867c282fe86988850a32
