### ISSUE TITLE
Code has Windows/DOS-style line endings which must be converted before running on Linux

### ISSUE THREAD

**Issue by danieljweinberg** [GurpreetKang/BitwardenDecrypt#20]
Hi, when I ran this for the first time on a Linux machine (Debian 11), I got the error 
`/usr/bin/env: ‘python3\r’: No such file or directory`
This indicates the "file was created or edited on a Windows system and uses Windows/DOS-style line endings (CR+LF), whereas Linux systems ... require Unix-style line endings (LF)." ([source](https://askubuntu.com/a/896880))
Per the suggestion in that post, I was able to fix this after running _dos2unix_ on the file, after which the file executed perfectly.
I believe this means that at some point the python code was saved on a Windows machine? I have not tested running the file on Windows, however if the intention is to generally run it on Linux then it may be best to save on Linux before pushing to github.
If I am missing something, let me know. Thank you!

**Comment by GurpreetKang** [comment]
Thanks for reporting this.  I'll need to do some testing to ensure changing this doesn't impact WIndows users, and if not I'll push out a fix.
