### ISSUE TITLE
Add support for Argon2 KDF

### ISSUE THREAD

**Issue by GurpreetKang** [GurpreetKang/BitwardenDecrypt#22]
Add support for [Argon2 KDF](https://bitwarden.com/help/kdf-algorithms/) (added in Bitwarden v2023.2.0).

**Comment by Davek145** [comment]
Hi, I have finished my modification of the BitwardenDecrypt script to support Argon2 KDF added in Bitwarden 2023.2.0. It is working well for vaults I have on my server. It is utilizing argon2-cffi library.
I do not have pull access to this repository, so I was not able to upload it as branch. Please, give my pull access and I will upload my script modification for your review.

**Comment by GurpreetKang** [comment]
@Davek145, thank you for your work on this.  You will need to fork this repo, make changes on a branch in your forked repo, and then create a pull request.

**Comment by Davek145** [comment]
Correct, log time I did it last time in git.
Here it is: [https://github.com/GurpreetKang/BitwardenDecrypt/pull/23#issue-1600188660](url)

**Comment by GurpreetKang** [comment]
Thanks for PR #23. It might be a few days until I have time to fully test it.

**Comment by GurpreetKang** [comment]
Closed by #31.
